interface Card {
  type: "master" | "natial" | "magic";
  skill?: string;
  ability?: string;
  element?: "earth" | "water" | "fire" | "heaven";
  subType?: "bow" | "wing" | "bowwing";
  mana: number;
  attack?: number;
  hp?: number;
}

export const cards: Record<string, Card> = {
  FIGHTER: {
    type: "master",
    ability: "+1 counterattack damage when attacked",
    mana: 1,
    attack: 2,
    hp: 20,
  },
  RANGER: {
    type: "master",
    subType: "bow",
    mana: 2,
    attack: 1,
    hp: 18,
  },
  SISTER: {
    type: "master",
    skill: "ATK +2 for target (cost: 2 mana)",
    mana: 3,
    attack: 1,
    hp: 18,
  },
  KNIGHT: {
    type: "master",
    skill: "ATK +1 for all ally cards (cost: 3 mana)",
    mana: 2,
    attack: 3,
    hp: 30,
  },
  THIEF: {
    type: "master",
    skill: "Draw a card from the deck (cost: 2 mana)",
    ability: "Can act twice in a row",
    mana: 2,
    attack: 1,
    hp: 26,
  },
  WITCH: {
    type: "master",
    skill: "Deal 4 damage to the target (cost: 4 mana)",
    mana: 5,
    attack: 2,
    hp: 24,
  },
  PALADIN: {
    type: "master",
    skill: "Revive 1 destroyed card at random (cost: 4 mana)",
    ability: "Recovers 1 HP every turn",
    mana: 4,
    attack: 3,
    hp: 30,
  },
  BEAST: {
    type: "master",
    skill: "Draw a card from the deck (cost: 1 mana)",
    ability: "2 counterattack damage when attacked",
    mana: 4,
    attack: 4,
    hp: 30,
  },
  SWORDSMAN: {
    type: "master",
    skill: "Deal 1 damage to a row of enemies (cost: 1 mana)",
    ability: "ATK +1 each time it defeats an enemy",
    mana: 4,
    attack: 3,
    hp: 27,
  },
  SORCERER: {
    type: "master",
    skill: "Generate one magic crystal on the field (cost: 3 mana)",
    mana: 4,
    attack: 1,
    hp: 25,
  },
  SHADOW: {
    type: "master",
    skill: "Destroy 1 enemy card (cost: 4 mana)",
    ability: "Can counterattack against ranged cards",
    subType: "bow",
    mana: 2,
    attack: 2,
    hp: 20,
  },
  SPIRIT: {
    type: "master",
    skill: "Target can act again (cost: 3 mana)",
    ability: "When HP is 10 or less, any Natial cards gain ATK and HP +1",
    mana: 5,
    attack: 1,
    hp: 20,
  },
  BIRD: {
    type: "master",
    skill: "Enemy loses one turn (cost: 3 mana)",
    mana: 3,
    attack: 2,
    hp: 22,
  },
  TYRANT: {
    type: "master",
    skill: "Deal 3 damage to all enemies (cost: 3 mana)",
    ability: "ATK and HP +2 for the cards to its left and right",
    mana: 4,
    attack: 5,
    hp: 30,
  },
  "MAGIC CRYSTAL": {
    type: "magic",
    ability:
      "ATK and HP +1, and mana +1. If the target is a Natial, it can use its skill again.",
    mana: 0,
  },
  MEDIC: {
    type: "magic",
    ability:
      "Recover 2 HP for the target and cancel seal. If the target is a Heaven card, ATK +1",
    mana: 1,
  },
  CONJURATE: {
    type: "magic",
    ability:
      "Seal the target’s action for two turns. If your master card is a Witch, seal for three turns",
    mana: 4,
  },
  VANISH: {
    type: "magic",
    ability:
      "Deal 6 damage to the target. If your master card is a Paladin, deal 7 damage",
    mana: 4,
  },
  UPTIDE: {
    type: "magic",
    ability:
      "ATK and HP +2 for all Water type cards, deals 2 damage to enemy Earth, Fire and Heaven cards",
    mana: 3,
  },
  BLAZE: {
    type: "magic",
    ability: "ATK +2 for the target card. If the target is a Fire card, ATK +3",
    mana: 2,
  },
  WALL: {
    type: "magic",
    ability:
      "Casts a wall that completely defends the target against one attack. If the target is an Earth card, recover 3 HP",
    mana: 2,
  },
  XSPELL: {
    type: "magic",
    ability: "Return 1 enemy Natial to to opponent’s deck",
    mana: 3,
  },
  REDUCE: {
    type: "magic",
    ability:
      "Halve the mana cost to summon one card from your hand (rounded up)",
    mana: 1,
  },
  DISASTER: {
    type: "magic",
    ability: "Deal 4 damage to a row of enemies",
    mana: 5,
  },
  "PA-RANCELL": {
    type: "natial",
    element: "earth",
    ability: "Defends adjacent cards to the left and right",
    mana: 1,
    attack: 1,
    hp: 1,
  },
  "D-ARMA": {
    type: "natial",
    element: "earth",
    skill: "Restores 2HP to the target",
    ability: "Can act twice",
    mana: 2,
    attack: 1,
    hp: 3,
  },
  "AE-FERRION": {
    type: "natial",
    element: "earth",
    subType: "bow",
    mana: 3,
    attack: 2,
    hp: 1,
  },
  "GIA-BRO": {
    type: "natial",
    element: "earth",
    skill: "Deal 2 damage to a row of enemies",
    mana: 4,
    attack: 2,
    hp: 5,
  },
  "DA-COLM": {
    type: "natial",
    element: "earth",
    ability: "+1 ATK for cards in the same row",
    mana: 6,
    attack: 6,
    hp: 8,
  },
  "BA-MADO": {
    type: "natial",
    element: "earth",
    subType: "wing",
    skill: "Seal target's action for two turns",
    ability: "ATK +1 each time it defeats an enemy",
    mana: 7,
    attack: 5,
    hp: 5,
  },
  REQU: {
    type: "natial",
    element: "water",
    ability: "Draw a card when leaves play",
    mana: 1,
    attack: 1,
    hp: 1,
  },
  MARME: {
    type: "natial",
    element: "water",
    skill: "Recovers 3HP for target",
    mana: 3,
    attack: 2,
    hp: 3,
  },
  ZAMILPEN: {
    type: "natial",
    element: "water",
    skill: "Seal target's action for one turn",
    mana: 4,
    attack: 4,
    hp: 3,
  },
  TARBYSS: {
    type: "natial",
    element: "water",
    ability: "Draw a card when leaves play",
    subType: "bow",
    mana: 5,
    attack: 3,
    hp: 3,
  },
  NEPTUNO: {
    type: "natial",
    element: "water",
    skill: "Deal 2 damage to one enemy",
    ability: "Shields cards to its left and right",
    mana: 7,
    attack: 5,
    hp: 7,
  },
  TENTARCH: {
    type: "natial",
    element: "water",
    skill: "Deal 4 damage to all enemies",
    mana: 8,
    attack: 6,
    hp: 9,
  },
  HEPETUS: {
    type: "natial",
    element: "fire",
    mana: 2,
    attack: 2,
    hp: 2,
  },
  DULLMDALLA: {
    type: "natial",
    element: "fire",
    skill: "Deal 1 damage to a row of enemies",
    ability: "ATK +1 each time it defeats an enemy",
    mana: 3,
    attack: 1,
    hp: 3,
  },
  BLYX: {
    type: "natial",
    element: "fire",
    subType: "bow",
    mana: 4,
    attack: 2,
    hp: 3,
  },
  OONVIEVLE: {
    type: "natial",
    element: "fire",
    ability: "ATK +1 each time it defeats an enemy",
    mana: 6,
    attack: 6,
    hp: 6,
  },
  GREON: {
    type: "natial",
    element: "fire",
    subType: "wing",
    ability: "Can act twice in a row",
    mana: 7,
    attack: 5,
    hp: 5,
  },
  ZENOSBLEAD: {
    type: "natial",
    element: "fire",
    skill: "Deal 5 damage to one enemy",
    ability: "ATK +2 each time it defeats an enemy",
    mana: 7,
    attack: 4,
    hp: 7,
  },
  PELITT: {
    type: "natial",
    element: "heaven",
    skill: "Cancel seal on target",
    subType: "wing",
    mana: 1,
    attack: 1,
    hp: 1,
  },
  "GENE-FOSS": {
    type: "natial",
    element: "heaven",
    skill: "Deal 2 damage to a row of enemies",
    subType: "wing",
    mana: 3,
    attack: 2,
    hp: 3,
  },
  "KYRIER-BELL": {
    type: "natial",
    element: "heaven",
    skill: "Deal 2 damage to a row of enemies",
    subType: "wing",
    mana: 4,
    attack: 5,
    hp: 3,
  },
  FIFENALL: {
    type: "natial",
    element: "heaven",
    skill: "Recover 6HP for target",
    ability: "Draw a card when leaves play",
    subType: "wing",
    mana: 4,
    attack: 2,
    hp: 6,
  },
  AMOLTAMISS: {
    type: "natial",
    element: "heaven",
    subType: "bowwing",
    ability: "ATK +2 when in front row",
    mana: 6,
    attack: 3,
    hp: 6,
  },
  "RAGNA-CROX": {
    type: "natial",
    element: "heaven",
    subType: "wing",
    skill: "Deal 3 damage to a row of enemies",
    ability: "+1 ATK for ally Heaven cards",
    mana: 8,
    attack: 5,
    hp: 7,
  },
};
